services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: medialibrary
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sysadmin6769
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medialibrary
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: sysadmin6769
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata: